services:
  - type: web
    name: wild-horizon-backend
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: cd Backend && npm install && npm run build
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
